version: "3.8"

services:
  onsquad-cache:
    container_name: onsquad-cache
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"

  onsquad-db:
    container_name: onsquad-db
    image: mysql:8-oracle
    restart: always
    expose:
      - 3306
    ports:
      - "9904:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../db/mysql/data:/var/lib/mysql
      - ../db/mysql/init:/docker-entrypoint-initdb.d
